export default[
    {
        id:1,
        img1:"../images/ele_girlwatch1.jpeg",
        title:"Handwatch",
        info:"Men Styled Slim Jeans",
        price:500,
        rating:"4.3",
        category:"watch",
        brand:"titan",
        mrp:"1000",
        offer:"76%"
    },
    {
        id:2,
        img1:"../images/ele_girlwatch2.jpeg",
        title:"black handwatch",
        info:"Men Styled Slim Jeans",
        price:700,
        rating:"4.3",
        category:"watch",
        brand:"titan",
        mrp:"1000",
        offer:"76%"
    },
    {
        id:3,
        img1:"../images/ele_girlwatch3.jpeg",
        title:"Girl handwatch",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"watch",
        brand:"titan",
        mrp:"2000",
        offer:"76%"
    },
    {
        id:4,
        img1:"../images/ele_girlwatch4.jpeg",
        title:"Smartwatch",
        info:"Men Styled Slim Jeans",
        price:2000,
        rating:"4.3",
        category:"watch",
        brand:"apple",
        mrp:"3000",
        offer:"76%"
    },
    {
        id:5,
        img1:"../images/ele_ipad1.jpeg",
        title:"T-shirt",
        info:"Men Styled Slim Jeans",
        price:60000,
        rating:"4.3",
        category:"ipad",
        brand:"apple",
        mrp:"70000",
        offer:"76%"
    },
    {
        id:6,
        img1:"../images/ele_iphone13.jpeg",
        title:"Full Sleeve",
        info:"Men Styled Slim Jeans",
        price:120000,
        rating:"4.3",
        category:"iphone",
        brand:"apple",
        mrp:"1,30,000",
        offer:"76%"
    },
    {
        id:7,
        img1:"../images/ele_iphone14.jpeg",
        title:"Full Sleev",
        info:"Men Styled Slim Jeans",
        price:70000,
        rating:"4.3",
        category:"iphone",
        brand:"apple",
        mrp:"90,000",
        offer:"76%"
    },
    {
        id:8,
        img1:"../images/ele_laptop1.jpeg",
        title:"Black t-shirt",
        info:"Men Styled Slim Jeans",
        price:120000,
        rating:"4.3",
        category:"laptop",
        brand:"apple",
        mrp:"1,50,000",
        offer:"76%"
    },
    {
        id:9,
        img1:"../images/ele_laptop2.jpeg",
        title:"Modern",
        info:"Men Styled Slim Jeans",
        price:80000,
        rating:"4.3",
        category:"laptop",
        brand:"dell",
        mrp:"100000",
        offer:"76%"

    },
    {
        id:10,
        img1:"../images/ele_laptop3.jpeg",
        title:"Levis",
        info:"Men Styled Slim Jeans",
        price:75000,
        rating:"4.3",
        category:"laptop",
        brand:"apple",
        mrp:"90000",
        offer:"76%"
    },
    {
        id:11,
        img1:"../images/ele_laptop4.jpeg",
        title:"Roadster",
        info:"Men Styled Slim Jeans",
        price:100000,
        rating:"4.3",
        category:"laptop",
        brand:"dell",
        mrp:"1,20,000",
        offer:"76%"
    },
    {
        id:12,
        img1:"../images/ele_menwatch1.jpeg",
        title:"Poerlook",
        info:"Men Styled Slim Jeans",
        price:20000,
        rating:"4.3",
        category:"watch",
        brand:"titan",
        mrp:"30000",
        offer:"76%"
    },
    {
        id:13,
        img1:"../images/ele_menwatch2.jpeg",
        title:"Road shooes",
        info:"Men Styled Slim Jeans",
        price:15000,
        rating:"4.3",
        category:"watch",
        brand:"titan",
        mrp:"20000",
        offer:"76%"
    },
    {
        id:14,
        img1:"../images/ele_menwatch3.jpeg",
        title:"Formal shooes",
        info:"Men Styled Slim Jeans",
        price:3000,
        rating:"4.3",
        category:"watch",
        brand:"titan",
        mrp:"40000",
        offer:"76%"
    },
    {
        id:15,
        img1:"../images/ele_redmi.jpeg",
        title:"Sport shooes",
        info:"Men Styled Slim Jeans",
        price:30000,
        rating:"4.3",
        category:"mobile",
        brand:"redmi",
        mrp:"40000",
        offer:"76%"
    },
    {
        id:16,
        img1:"../images/ele_oppo.jpeg",
        title:"Snekers shooes",
        info:"Men Styled Slim Jeans",
        price:25000,
        rating:"4.3",
        category:"mobile",
        brand:"oppo",
        mrp:"30000",
        offer:"76%"
    },
    

]