export default[
    {
        id:1,
        img1:"../images/menjeans_1.jpeg",
        title:"Straight Jeans",
        info:"Men Styled Slim Jeans",
        price:2559,
        rating:"4.3",
        category:"Jeans",
        brand:"Rooadster",
        mrp:"4000",
        offer:"76%",
     
    },
    {
        id:2,
        img1:"../images/mensjeans_2.jpeg",
        title:"Black jeans",
        info:"Men Styled Slim Jeans",
        price:3000,
        rating:"4.3",
        category:"Jeans",
        brand:"FABdon",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:3,
        img1:"../images/mens_jeans_3.jpeg",
        title:"Blue jeans",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"Jeans",
        brand:"Rooadster",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:4,
        img1:"../images/mens_jeans_4.jpeg",
        title:"Regular jeans",
        info:"Men Styled Slim Jeans",
        price:500,
        rating:"4.3",
        category:"Jeans",
        brand:"FABdon",
        mrp:"4000",
        offer:"76%"
        
    },
    {
        id:5,
        img1:"../images/tshirt_1.jpeg",
        title:"T-shirt",
        info:"Men Styled Slim Jeans",
        price:500,
        rating:"4.3",
        category:"tshirt",
        brand:"Adidas",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:6,
        img1:"../images/tshirt_2.jpeg",
        title:"Full Sleeve",
        info:"Men Styled Slim Jeans",
        price:2000,
        rating:"4.3",
        category:"tshirt",
        brand:"max",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:7,
        img1:"../images/tshirt_3.jpeg",
        title:"Full Sleev",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"tshirt",
        brand:"Rooadster",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:8,
        img1:"../images/tshirt_4.jpeg",
        title:"Black t-shirt",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"tshirt",
        brand:"max",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:9,
        img1:"../images/jacket_men_1.jpeg",
        title:"Modern",
        info:"Men Styled Slim Jeans",
        price:3000,
        rating:"4.3",
        category:"jacket",
        brand:"Adidas",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:10,
        img1:"../images/jacket_men_2.jpeg",
        title:"Levis",
        info:"Men Styled Slim Jeans",
        price:2500,
        rating:"4.3",
        category:"jacket",
        brand:"Rooadster",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:11,
        img1:"../images/jacket_men_3.jpeg",
        title:"Roadster",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"jacket",
        brand:"Adidas",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:12,
        img1:"../images/jacket_men_4.jpeg",
        title:"Poerlook",
        info:"Men Styled Slim Jeans",
        price:2000,
        rating:"4.3",
        category:"jacket",
        brand:"max",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:13,
        img1:"../images/shooes_men_1.jpeg",
        title:"Road shooes",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"shoes",
        brand:"Rooadster",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:14,
        img1:"../images/shooes_men_3.jpeg",
        title:"Formal shooes",
        info:"Men Styled Slim Jeans",
        price:2000,
        rating:"4.3",
        category:"shoes",
        brand:"sparks",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:15,
        img1:"../images/shooes_men_4.jpeg",
        title:"Sport shooes",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"shoes",
        brand:"sparks",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:16,
        img1:"../images/shooes_mens_2.jpeg",
        title:"Snekers shooes",
        info:"Men Styled Slim Jeans",
        price:1200,
        rating:"4.3",
        category:"shoes",
        brand:"Rooadster",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:17,
        img1:"../images/formal_men_5.jpeg",
        title:"white formal",
        info:"Men Styled Slim Jeans",
        price:500,
        rating:"4.3",
        category:"formal",
        brand:"Raymond",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:18,
        img1:"../images/formal_men_2.jpeg",
        title:"Styled formal",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"formal",
        brand:"Adidas",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:19,
        img1:"../images/formal_men_3.jpeg",
        title:"Fit formal",
        info:"Men Styled Slim Jeans",
        price:1200,
        rating:"4.3",
        category:"formal",
        brand:"Raymond",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:20,
        img1:"../images/formal_men_4.jpeg",
        title:"English navey",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"formal",
        brand:"Adidas",
        mrp:"4000",
        offer:"76%"
    }

]