export default[
    {
        id:1,
        img1:"../images/girl_jacket_3.jpg",
        title:"modern jacket",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"jacket",
        brand:"aurelia",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:2,
        img1:"../images/girl_jeans_1.jpeg",
        title:"Modern jenes",
        info:"Men Styled Slim Jeans",
        price:1200,
        rating:"4.3",
        category:"jeans",
        brand:"pantaloons",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:3,
        img1:"../images/girl_saree_2.jpeg",
        title:"slik saree",
        info:"Men Styled Slim Jeans",
        price:3000,
        rating:"4.3",
        category:"saree",
        brand:"kalyani",
        mrp:"4000",
        offer:"76%"

    },
    {
        id:4,
        img1:"../images/girl_tshirt_1.jpeg",
        title:"tshirt",
        info:"Men Styled Slim Jeans",
        price:600,
        rating:"4.3",
        category:"tshirt",
        brand:"levis",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:5,
        img1:"../images/girl_jeans_2.jpeg",
        title:"blue jeans",
        info:"Men Styled Slim Jeans",
        price:2500,
        rating:"4.3",
        category:"jeans",
        brand:"zara",
        mrp:"4000",
        offer:"76%",
    },
    {
        id:6,
        img1:"../images/girl_saree_1.jpeg",
        title:"Fmodern saree",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"saree",
        mrp:"4000",
        offer:"76%",
        brand:"kalyani"
    },
    {
        id:7,
        img1:"../images/girl_shooe_2.jpg",
        title:"Causal shooes",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"shoes",
        mrp:"4000",
        offer:"76%",
        brand:"aurelia"
    },
    {
        id:8,
        img1:"../images/girl_tshirt_2.jpeg",
        title:"fancy tshirt",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"shoes",
        mrp:"4000",
        offer:"76%",
        brand:"pantaloons"
    },
    {
        id:9,
        img1:"../images/girl_saree_3.jpeg",
        title:"plain saree",
        info:"Men Styled Slim Jeans",
        price:1200,
        rating:"4.3",
        category:"saree",
        mrp:"4000",
        offer:"76%",
        brand:"kalyani"
    },
    {
        id:10,
        img1:"../images/girl_shooe_3.jpeg",
        title:"fancy shooes",
        info:"Men Styled Slim Jeans",
        price:500,
        rating:"4.3",
        category:"shoes",
        mrp:"4000",
        offer:"76%",
        brand:"Pantaloons"
    },
    {
        id:11,
        img1:"../images/girl_jeans_3.jpeg",
        title:"Regular jeans",
        info:"Men Styled Slim Jeans",
        price:2000,
        rating:"4.3",
        category:"jeans",
        mrp:"4000",
        offer:"76%",
        brand:"Aurelia"
    },
    {
        id:12,
        img1:"../images/girl_tshirt_4.jpeg",
        title:"simple tshirt",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"tshirt",
        brand:"Levis",
        mrp:"4000",
        offer:"76%"
    },
    {
        id:13,
        img1:"../images/girl_tshirt_3.jpeg",
        title:"Sweetshirt",
        info:"Men Styled Slim Jeans",
        price:1000,
        rating:"4.3",
        category:"tshirt",
        mrp:"4000",
        offer:"76%",
        brand:"Zara"
    },
    {
        id:14,
        img1:"../images/girl_saree_4.jpeg",
        title:"Modern saree",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"saree",
        mrp:"4000",
        offer:"76%",
        brand:"westside"

    },
    {
        id:15,
        img1:"../images/girl_shooe_4.jpeg",
        title:"Roadsters shooes",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"shoes",
        mrp:"4000",
        offer:"76%",
        brand:"levis"
    },
    {
        id:16,
        img1:"../images/girl_jacket_2.jpeg",
        title:"Black jacket",
        info:"Men Styled Slim Jeans",
        price:3000,
        rating:"4.3",
        category:"jacket",
        mrp:"4000",
        offer:"76%",
        brand:"westside"
    },
    {
        id:17,
        img1:"../images/girl_sandel_1.jpeg",
        title:"Hill sandel",
        info:"Men Styled Slim Jeans",
        price:500,
        rating:"4.3",
        mrp:4000,
        offer:"76%",
        category:"shoes",
        brand:"pantaloons"
    },
    {
        id:18,
        img1:"../images/girl_shot_1.jpeg",
        title:"Black shots",
        info:"Men Styled Slim Jeans",
        price:700,
        rating:"4.3",
        category:"shorts",
        mrp:"4000",
        offer:"76%",
        brand:"westside"
    },
    {
        id:19,
        img1:"../images/girl_jacket_1.jpeg",
        title:"moden jacket",
        info:"Men Styled Slim Jeans",
        price:1500,
        rating:"4.3",
        category:"jacket",
        mrp:"4000",
        offer:"76%",
        brand:"westside"
    },
    {
        id:20,
        img1:"../images/girl_shot_2.jpeg",
        title:"pink shots",
        info:"Men Styled Slim Jeans",
        price:700,
        rating:"4.3",
        category:"shorts",
        mrp:"4000",
        offer:"76%",
        brand:"westside"
    }

]